/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import alat.AlatDivingForm;
import login.LoginDAOImp;
import login.LoginForm;
import peminjaman.PeminjamanForm;
import pengembalian.DataSewa;
import pengembalian.PengembalianAlat;
import user.UserForm;


public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    
    
    public Main() {
        initComponents();
        /*
        syntak dibawah berfungsi menu-menu yang nantinya akan hidup saat selesai login
        */
        menuLogout.setVisible(false);
        menuAlat.setVisible(false);
        menuPengembalian.setVisible(false);
        menuPinjam.setVisible(false);
        menuUser.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuAkses = new javax.swing.JMenu();
        menuLogin = new javax.swing.JMenuItem();
        menuLogout = new javax.swing.JMenuItem();
        menuPinjam = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        menuPengembalian = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        menuAlat = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        menuUser = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/gambar.JPG"))); // NOI18N

        menuAkses.setText("AKSES");

        menuLogin.setText("LOGIN");
        menuLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLoginActionPerformed(evt);
            }
        });
        menuAkses.add(menuLogin);

        menuLogout.setText("LOGOUT");
        menuLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLogoutActionPerformed(evt);
            }
        });
        menuAkses.add(menuLogout);

        jMenuBar1.add(menuAkses);

        menuPinjam.setText("PEMINJAMAN");

        jMenuItem5.setText("TAMBAH PEMINJAMAN");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        menuPinjam.add(jMenuItem5);

        jMenuItem6.setText("DATA PINJAMAN");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        menuPinjam.add(jMenuItem6);

        jMenuBar1.add(menuPinjam);

        menuPengembalian.setText("PENGEMBALIAN");

        jMenuItem7.setText("PENGEMBALIAN");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        menuPengembalian.add(jMenuItem7);

        jMenuBar1.add(menuPengembalian);

        menuAlat.setText("ALAT");

        jMenuItem4.setText("DATA ALAT");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        menuAlat.add(jMenuItem4);

        jMenuBar1.add(menuAlat);

        menuUser.setText("USER");

        jMenuItem3.setText("DATA USER");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        menuUser.add(jMenuItem3);

        jMenuBar1.add(menuUser);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        /*
        syntak dibawah berfungsi memanggil/memunculkan form peminjaman
        */
        PeminjamanForm peminjaman = new PeminjamanForm();
        peminjaman.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        /*
        syntak dibawah berfungsi memanggil/memunculkan form pengembalian
        */
        PengembalianAlat datapengembalian = new PengembalianAlat();
        datapengembalian.setVisible(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        /*
        syntak dibawah berfungsi memanggil/memunculkan form data alat
        */
        AlatDivingForm alat = new AlatDivingForm();
        alat.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        /*
        syntak dibawah berfungsi memanggil/memunculkan form data user
        */
        UserForm user = new UserForm();
        user.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void menuLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLoginActionPerformed
        /*
        syntak dibawah berfungsi memanggil/memunculkan form login
        */
        LoginForm login = new LoginForm();
        login.setVisible(true);
        hide();
    }//GEN-LAST:event_menuLoginActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        /*
        syntak dibawah berfungsi memanggil/memunculkan form data penyewaan
        */
        DataSewa data=new DataSewa();
        data.setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void menuLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLogoutActionPerformed
        /*
        syntak dibawah berfungsi mereset id,nama user menggunakan method logout
        yang ada di loginDAOImp.java lalu setelah direset menu2 yang ada di main form dikembalikan
        seperti sebelum login
        */
        LoginDAOImp log=new LoginDAOImp();
        log.logout();
        menuLogout.setVisible(false);
        menuAlat.setVisible(false);
        menuPengembalian.setVisible(false);
        menuPinjam.setVisible(false);
        menuUser.setVisible(false);
        menuLogin.setVisible(true);
    }//GEN-LAST:event_menuLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenu menuAkses;
    public static javax.swing.JMenu menuAlat;
    public static javax.swing.JMenuItem menuLogin;
    public static javax.swing.JMenuItem menuLogout;
    public static javax.swing.JMenu menuPengembalian;
    public static javax.swing.JMenu menuPinjam;
    public static javax.swing.JMenu menuUser;
    // End of variables declaration//GEN-END:variables
}
